modLoader="javafml" #mandatory
loaderVersion="[27,)"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="storageblockexample"
version="${file.jarVersion}"
displayName="Storage Block Example"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="The Forge and FML guys, for making forge"
authors="KingIceCream"
description="Storage Block Example"

[[dependencies.storageblockexample]] #optional
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.storageblockexample]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"